version: "3"
services:
    backend:
       container_name: backend      
       build: 
          context: ./backend
          dockerfile: ./deploy/Dockerfile
       networks:
          - envoymesh 
       ports: 
            - "3333:3333"
    frontend:
       container_name: frontend
       build: 
          context: ./frontend
          dockerfile: ./deploy/Dockerfile
       volumes:
         - './:/frontend'
       networks:
         envoymesh:
           aliases:
             - frontend
       environment:
         - SERVICE_NAME=frontend   
         - CHOKIDAR_USEPOLLING=true   
       ports:
         - 3000:3000
       command: npm run dev
networks:
  envoymesh: {}